name: markdownlint
on:
  pull_request:
  push:
    paths: ["**/*.md", ".markdownlint.json"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run PowerShell Markdown formatting script
        shell: pwsh
        run: |
          ./tools/fix_md_blanklines.ps1
      - name: Run PowerShell Markdown formatting script
        shell: pwsh
        run: |
          ./tools/fix_md_blanklines.ps1
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md
          config: .markdownlint.json
